### PR TITLE
Mexican Spanish Translation

### PR DESCRIPTION
**Pull request by TheLegendofSaram**
Just a joke translation

### CODE REVIEW

**Comment by Kira-NT** [comment]
Why is this a "joke translation" tho? I have nothing against Spanish! :)

Just one thing - is it possible to make the translation string shorter? I'm afraid it won't fit properly without being cut off. As far as my understanding goes, the translation you suggested is somewhat literal, "Window without borders". Is it possible to say the same thing in one or maybe two words, just like with the English version - "Borderless"?

**Comment by TheLegendofSaram** [comment]
Awww thats wholesome AHAHA. it's a "joke" because its just one string of translation, and sure, i can compact the translation

**Review by TheLegendofSaram — COMMENTED** [review]
Changed to "Sin boders"

**Comment by TheLegendofSaram** [comment]
there it is, I changed it to "Sin bordes" which literally means "borderless" or "without borders"

**Comment by Kira-NT** [comment]
Merged in #7 :)

**Pull request closed without merging**
